In [1]:
# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler

In [3]:
# Load the dataset
df = pd.read_csv('animal_bites.csv')
# Display the first row of the dataframe to verify successful loading
df.head(1)

,bite_date,SpeciesIDDesc,BreedIDDesc,GenderIDDesc,color,vaccination_yrs,vaccination_date,victim_zip,AdvIssuedYNDesc,WhereBittenIDDesc,quarantine_date,DispositionIDDesc,head_sent_date,release_date,ResultsIDDesc
0,1985-05-05 00:00:00,DOG,NaN,FEMALE,LIG. BROWN,1.0,1985-06-20 00:00:00,40229,NO,BODY,1985-05-05 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN

In [7]:
# Display the current column names
print("Current column names:")
print(df.columns)

# Define the new column names
new_column_names = {
    'SpeciesIDDesc': 'specie',
    'BreedIDDesc': 'breed',
    'vaccination_yrs': 'years_since_last_vaccination',
    'GenderIDDesc': 'gender',
    'AdvIssuedYNDesc': 'advised_issued',
    'WhereBittenIDDesc': 'where_victim_was_bitten',
    'DispositionIDDesc': 'animal_released_from_quarantine',
    'head_sent_date': 'head_animal_sent_to_lab',
    'ResultsIDDesc': 'result_for_rabies',
 
    # Add more mappings as needed
}

# Rename the current columns to a more intuitive description 
df.rename(columns=new_column_names, inplace=True)

# Display the updated column names
print("\nUpdated column names:")
print(df.columns)

df.head(1)

Current column names:
Index(['bite_date', 'specie', 'breed', 'gender', 'color', 'vaccination_yrs',
       'vaccination_date', 'victim_zip', 'advised_issued',
       'where_victim_was_bitten', 'quarantine_date',
       'animal_released_from_quarantine', 'head_animal_sent_to_lab',
       'release_date', 'result_for_rabies'],
      dtype='object')

Updated column names:
Index(['bite_date', 'specie', 'breed', 'gender', 'color',
       'years_since_last_vaccination', 'vaccination_date', 'victim_zip',
       'advised_issued', 'where_victim_was_bitten', 'quarantine_date',
       'animal_released_from_quarantine', 'head_animal_sent_to_lab',
       'release_date', 'result_for_rabies'],
      dtype='object')

,bite_date,specie,breed,gender,color,years_since_last_vaccination,vaccination_date,victim_zip,advised_issued,where_victim_was_bitten,quarantine_date,animal_released_from_quarantine,head_animal_sent_to_lab,release_date,result_for_rabies
0,1985-05-05 00:00:00,DOG,NaN,FEMALE,LIG. BROWN,1.0,1985-06-20 00:00:00,40229,NO,BODY,1985-05-05 00:00:00,UNKNOWN,NaN,NaN,UNKNOWN